### ISSUE TITLE
User and password of demo site are wrong

### ISSUE THREAD

**Issue by valle6** [networking/init-cms-sandbox#18]
In GitHub and http://www.initcms.com/demo.html the user and password of demo site are wrong: admin, initcms. Only in demo site page, http://demo.initcms.com/, they are correct: demo_en, demo12. The admin demo page exists only in german, not in english.

**Comment by rogerized** [comment]
Hi,
we have a new demo site and there will a new sale site on initcms.com soon too. I updated the login credentials, so that it is accurate now, sorry for inconvenience.

The demo exists in two languages: english and german. Both in Frontend and Backend. But you have to differentiate the content language from the UI language in the Backend. So with the login you choose your backend language (demo_en for english, demo_de for german), but the content (Pages) is available in english and german anyway. You can choose the content language under "Pages" ("Seiten") with the first dropdown and press search.

Hope everything is clear and works for you.
